version: "3"

services:
  php-server:
    build: .docker/docker
    image: php
    depends_on:
      - mariadb
    volumes:
      - ./:/application

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - .docker/nginx/cert:/etc/nginx/cert:cached
    depends_on:
      - php-server
